name: Deploy to Firebase project Develop (develop)

on:
  push:
    branches: [develop]

jobs:
  build:
    name: ðŸ”§ Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: ðŸ’ª Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: ðŸ–¥ Checkout repo
        uses: actions/checkout@v2
      - name: Create .env file
        run: echo "${{ secrets.ENV }}" > .env
      - name: ðŸš© NPM Install & Build
        run: |
          yarn install
          yarn run build
      - name: ðŸ“¤ Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:develop,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
