name: Deploy to Firebase project Develop (staging)

on:
  push:
    branches: [develop]

jobs:
  build:
    name: ðŸ”§ Build & ðŸ“® Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: ðŸ’ª Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: ðŸ–¥ Checkout repo
        uses: actions/checkout@v2
      - name: ðŸš© NPM Install & Build
        run: |
          yarn install
          yarn run build
      - name: ðŸ“¤ Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAYA_CHI46_WEB }}'
          channelId: live
          projectId: kaya-chi46-web
